// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$0 from "./sections/Hero.tsx";
import * as $$$$$$1 from "./sections/Footer.tsx";
import * as $$$$$$2 from "./sections/Theme/Theme.tsx";
import * as $$$$$$3 from "./sections/SimpleTextList.tsx";
import * as $$$$$$4 from "./sections/ParagraphList.tsx";
import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";

const manifest = {
  "sections": {
    "deco-sites/tavano-start/sections/Footer.tsx": $$$$$$1,
    "deco-sites/tavano-start/sections/Hero.tsx": $$$$$$0,
    "deco-sites/tavano-start/sections/ParagraphList.tsx": $$$$$$4,
    "deco-sites/tavano-start/sections/SimpleTextList.tsx": $$$$$$3,
    "deco-sites/tavano-start/sections/Theme/Theme.tsx": $$$$$$2,
  },
  "apps": {
    "deco-sites/tavano-start/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/tavano-start/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/tavano-start",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
